GoalApp/config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :goals, only: [:index]
  end
  resources :comments, only: [:create, :destroy]
  resources :user_comments, only: [:create, :destroy]
  resources :goals, except: [:index]
  resource :session
end

GoalApp/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :user_id, :goal_id, presence: true

  belongs_to :user
  belongs_to :goal
end

GoalApp/app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :body, :user_id, presence: true

  belongs_to :user
  has_many :comments
end

GoalApp/app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :session_token, presence: true
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :password, length: { minimum: 6, allow_nil: true }


  after_initialize :ensure_session_token

  has_many :goals
  has_many :comments
  has_many :user_comments
  has_many :authored_user_comments,
    class_name: "UserComment",
    foreign_key: :author_id

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && user.is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

GoalApp/app/models/user_comment.rb
class UserComment < ActiveRecord::Base
  validates :user_id, :author_id, :body, presence: true

  belongs_to :user
  belongs_to :author, class_name: "User"
end

GoalApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = @current_user.reset_session_token!
  end

  def sign_out
    return unless logged_in?
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

end

GoalApp/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_login
  def create
    @comment = current_user.comments.new(comment_params)

    if @comment.save
      redirect_to goal_url(@comment.goal_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to goal_url(@comment.goal_id)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to goal_url(@comment.goal_id)
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :goal_id)
  end
end

GoalApp/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_filter :require_login
  def create
    # @goal = Goal.new(goals_params)
    # @goal.user_id = current_user.id

    @goal = current_user.goals.new(goals_params)

    if @goal.save
      redirect_to user_goals_url(@goal.user_id)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def new
    @goal = Goal.new
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])

    if @goal.update(goals_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_goals_url(@goal.user_id)
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def index
    @user = User.find(params[:user_id])
    @goals = @user.goals
  end

  private
  def goals_params
    params.require(:goal).permit(:body, :completed, :private)
  end
end

GoalApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(username, password)
    return if user.nil?
    sign_in(user)
    redirect_to users_url
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end

  private
  def username
    params[:user][:username]
  end

  def password
    params[:user][:password]
  end
end

GoalApp/app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController

  def create
    @comment = current_user.authored_user_comments.new(user_comment_params)

    if @comment.save
      redirect_to user_url(@comment.user_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to user_url(@comment.user_id)
    end
  end

  def destroy
    @comment = UserComment.find(params[:id])
    @comment.destroy
    redirect_to user_url(@comment.user_id)
  end

  private
  def user_comment_params
    params.require(:user_comment).permit(:user_id, :body)
  end
end

GoalApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to users_url
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

GoalApp/app/helpers/application_helper.rb
module ApplicationHelper
end

GoalApp/app/helpers/comments_helper.rb
module CommentsHelper
end

GoalApp/app/helpers/goals_helper.rb
module GoalsHelper
end

GoalApp/app/helpers/session_helper.rb
module SessionHelper
end

GoalApp/app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

GoalApp/app/helpers/users_helper.rb
module UsersHelper
end

GoalApp/app/views/comments/_form.html.erb
<h2>Add Comment</h2>
<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>
  <input type="hidden" name="comment[goal_id]" value="<%= params[:id] %>">
  <label for="comment_body">Comment body</label>
  <input type="string" name="comment[body]" id="comment_body">
  <input type="submit" value="Add Comment">
</form>

GoalApp/app/views/goals/edit.html.erb
<h1>Edit Goal</h1>
<form action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>
  <input type="hidden" name="_method" value="patch">
  <label for="goal_body">Body:</label>
  <textarea name="goal[body]" value="" id="goal_body"><%= @goal.body %></textarea>
  <label for="goal_private">Private?</label>
  Y<input type="radio" name="goal[private]" value="true" id="goal_private" <%= "checked" if @goal.private %>>
  N<input type="radio" name="goal[private]" value="false" id="goal_private" <%= "checked" unless @goal.private %>>

  <label for="goal_completed">Completed?</label>
  Y<input type="radio" name="goal[completed]" value="true" id="goal_completed" <%= "checked" if @goal.completed %>>
  N<input type="radio" name="goal[completed]" value="false" id="goal_completed" <%= "checked" unless @goal.completed %>>
  <input type="submit" value="Update Goal!">
</form>

GoalApp/app/views/goals/index.html.erb
<h1>Goals for: <%= @user.username %></h1>


<ul>
  <% @goals.each do |goal| %>
    <li><%= link_to goal.body, goal_url(goal) %>
    <%= button_to "Delete Goal :(", goal_url(goal), method: :delete %>
   <%= link_to "Edit Goal", edit_goal_url(goal) %></li>
  <% end %>
</ul>

<%= link_to "Add Goal", new_goal_url %>

GoalApp/app/views/goals/new.html.erb
<h1>Add Goal</h1>
<%= render 'shared/errors' %>

<form action='<%= goals_url %>' method="post">
  <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>

  <label for="body">Body:</label>
  <textarea name="goal[body]" id="body" rows="8" cols="40"><%= @goal.body %></textarea>

  <label for="private">Private Goal?</label>
  <input type="checkbox" name="goal[private]" value="<%= true %>">

  <input type="submit" value="Add Goal">
</form>

GoalApp/app/views/goals/show.html.erb
<h1><%= @goal.body %></h1>
<%= render 'shared/errors' %>
<%= "Private" if @goal.private %>
<br>
<%= "Complete" if @goal.completed %>
<br>
<%= render "comments/form" %>
<ul>
  <% @goal.comments.each do |comment| %>
    <li><%= comment.body %></li>
    <%= button_to "Delete Comment", comment_url(comment), method: :delete %>
  <% end %>
</ul>
<%= link_to "All Goals", user_goals_url(@goal.user_id) %>

GoalApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
    <%= button_to "Sign Out", session_url, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_session_url %>
    <%= link_to "Sign Up", new_user_url %>
  <% end %>

<%= yield %>

</body>
</html>

GoalApp/app/views/session/new.html.erb
<h1>Log In</h1>

<form action='<%= session_url %>' method="post">
  <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>

  <label for="username">Username:</label>
  <input type="text" name="user[username]" id="username" value="">

  <label for="password">Password:</label>
  <input type="password" name="user[password]" id="password" value="">

  <input type="submit" value="Log In">

</form>

GoalApp/app/views/shared/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

GoalApp/app/views/user_comments/_form.html.erb
<h2>Add Comment</h2>
<form action="<%= user_comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>
  <input type="hidden" name="user_comment[user_id]" value="<%= params[:id] %>">
  <label for="user_comment_body">Comment body</label>
  <input type="string" name="user_comment[body]" id="user_comment_body">
  <input type="submit" value="Add Comment">
</form>

GoalApp/app/views/users/index.html.erb
<h1>Home Page</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= user.username %></li>
  <% end %>
</ul>

GoalApp/app/views/users/new.html.erb
<h1>New User</h1>

<form action='<%= users_url %>' method="post">
  <input type="hidden" name="authenticity_token" value='<%= form_authenticity_token %>'>

  <label for="username">Username:</label>
  <input type="text" name="user[username]" id="username" value="">

  <label for="password">Password:</label>
  <input type="password" name="user[password]" id="password" value="">

  <input type="submit" value="Create User">

</form>

GoalApp/app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<%= render 'shared/errors' %>

<%= render "user_comments/form" %>
<ul>
  <% @user.user_comments.each do |comment| %>
    <li><%= comment.body %></li>
    <%= button_to "Delete Comment", user_comment_url(comment), method: :delete %>
  <% end %>
</ul>